name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./maintenance-dashboard

      - name: Build React app
        run: npm run build
        working-directory: ./maintenance-dashboard
        env:
          REACT_APP_HUGGING_FACE_API_KEY: ${{ secrets.HUGGING_FACE_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./maintenance-dashboard/build
          cname: your-custom-domain.com # Optional: Replace with your custom domain if you have one
